/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author MrDrulix
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radGroup_Pedido = new javax.swing.ButtonGroup();
        pnl_Pedido_Cliente = new javax.swing.JPanel();
        cbox_Pedido_Cliente_Busqueda = new javax.swing.JComboBox();
        txt_Pedido_Cliente_Buscar = new javax.swing.JTextField();
        btn_Pedido_Cliente_Buscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Pedido_Cliente_Busqueda = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        eti_Pedido_Cliente_Nombre = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        eti_Pedido_Cliente_Apellidos = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        eti_Pedido_Cliente_Domicilio = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        eti_Pedido_Cliente_Correo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        eti_Pedido_Cliente_Dni = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        eti_Pedido_Cliente_Telefono = new javax.swing.JLabel();
        pnl_Pedido_Proveedor = new javax.swing.JPanel();
        cbox_Pedido_Proveedor_Busqueda1 = new javax.swing.JComboBox();
        txt_Pedido_Proveedor_Buscar = new javax.swing.JTextField();
        btn_Pedido_Proveedor_Buscar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_Pedido_Proveedor_Busqueda = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        eti_Pedido_Proveedor_CIF = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        eti_Pedido_Proveedor_DSocial = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rad_Pedido_Cliente = new javax.swing.JRadioButton();
        rad_Pedido_Proveedor = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_Pedido_ArticulosPedidos = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_Pedido_Articulos = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pnl_Pedido_ClienteProveedor = new javax.swing.JPanel();
        btn_Pedido_Cancelar = new javax.swing.JButton();
        btn_Pedido_HacerPedido = new javax.swing.JButton();

        pnl_Pedido_Cliente.setBackground(new java.awt.Color(255, 255, 255));
        pnl_Pedido_Cliente.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente"));

        cbox_Pedido_Cliente_Busqueda.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dni", "Nombre", "Apellidos" }));

        btn_Pedido_Cliente_Buscar.setText("Buscar");

        tbl_Pedido_Cliente_Busqueda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_Pedido_Cliente_Busqueda);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Nombre:");

        eti_Pedido_Cliente_Nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eti_Pedido_Cliente_Nombre.setText("NombreSelect");
        eti_Pedido_Cliente_Nombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Apellidos:");

        eti_Pedido_Cliente_Apellidos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eti_Pedido_Cliente_Apellidos.setText("ApellidosSelect");
        eti_Pedido_Cliente_Apellidos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Domicilio:");

        eti_Pedido_Cliente_Domicilio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eti_Pedido_Cliente_Domicilio.setText("DomicilioSelect");
        eti_Pedido_Cliente_Domicilio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Correo:");

        eti_Pedido_Cliente_Correo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eti_Pedido_Cliente_Correo.setText("CorreoSelect");
        eti_Pedido_Cliente_Correo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Dni:");

        eti_Pedido_Cliente_Dni.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eti_Pedido_Cliente_Dni.setText("DniSelect");
        eti_Pedido_Cliente_Dni.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Telefono:");

        eti_Pedido_Cliente_Telefono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eti_Pedido_Cliente_Telefono.setText("TelefonoSelect");
        eti_Pedido_Cliente_Telefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pnl_Pedido_ClienteLayout = new javax.swing.GroupLayout(pnl_Pedido_Cliente);
        pnl_Pedido_Cliente.setLayout(pnl_Pedido_ClienteLayout);
        pnl_Pedido_ClienteLayout.setHorizontalGroup(
            pnl_Pedido_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Pedido_ClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_Pedido_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(pnl_Pedido_ClienteLayout.createSequentialGroup()
                        .addComponent(cbox_Pedido_Cliente_Busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Pedido_Cliente_Buscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Pedido_Cliente_Buscar))
                    .addGroup(pnl_Pedido_ClienteLayout.createSequentialGroup()
                        .addGroup(pnl_Pedido_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnl_Pedido_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_Pedido_ClienteLayout.createSequentialGroup()
                                .addComponent(eti_Pedido_Cliente_Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(eti_Pedido_Cliente_Apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_Pedido_ClienteLayout.createSequentialGroup()
                                .addComponent(eti_Pedido_Cliente_Dni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(eti_Pedido_Cliente_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(eti_Pedido_Cliente_Domicilio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eti_Pedido_Cliente_Correo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        pnl_Pedido_ClienteLayout.setVerticalGroup(
            pnl_Pedido_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Pedido_ClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_Pedido_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbox_Pedido_Cliente_Busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Pedido_Cliente_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Pedido_Cliente_Buscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_Pedido_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(eti_Pedido_Cliente_Nombre)
                    .addComponent(jLabel4)
                    .addComponent(eti_Pedido_Cliente_Apellidos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_Pedido_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(eti_Pedido_Cliente_Domicilio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_Pedido_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(eti_Pedido_Cliente_Correo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_Pedido_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(eti_Pedido_Cliente_Dni)
                    .addComponent(jLabel8)
                    .addComponent(eti_Pedido_Cliente_Telefono))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_Pedido_Proveedor.setBackground(new java.awt.Color(255, 255, 255));
        pnl_Pedido_Proveedor.setBorder(javax.swing.BorderFactory.createTitledBorder("Proveedor"));

        cbox_Pedido_Proveedor_Busqueda1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CIF", "Denominacion Social" }));

        btn_Pedido_Proveedor_Buscar.setText("Buscar");

        tbl_Pedido_Proveedor_Busqueda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbl_Pedido_Proveedor_Busqueda);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("CIF:");

        eti_Pedido_Proveedor_CIF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eti_Pedido_Proveedor_CIF.setText("CIFSelect");
        eti_Pedido_Proveedor_CIF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Denominación Social:");

        eti_Pedido_Proveedor_DSocial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eti_Pedido_Proveedor_DSocial.setText("DenominacionSocialSelect");
        eti_Pedido_Proveedor_DSocial.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pnl_Pedido_ProveedorLayout = new javax.swing.GroupLayout(pnl_Pedido_Proveedor);
        pnl_Pedido_Proveedor.setLayout(pnl_Pedido_ProveedorLayout);
        pnl_Pedido_ProveedorLayout.setHorizontalGroup(
            pnl_Pedido_ProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Pedido_ProveedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_Pedido_ProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                    .addGroup(pnl_Pedido_ProveedorLayout.createSequentialGroup()
                        .addComponent(cbox_Pedido_Proveedor_Busqueda1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Pedido_Proveedor_Buscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Pedido_Proveedor_Buscar))
                    .addGroup(pnl_Pedido_ProveedorLayout.createSequentialGroup()
                        .addGroup(pnl_Pedido_ProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnl_Pedido_ProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(eti_Pedido_Proveedor_CIF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eti_Pedido_Proveedor_DSocial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        pnl_Pedido_ProveedorLayout.setVerticalGroup(
            pnl_Pedido_ProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Pedido_ProveedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_Pedido_ProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbox_Pedido_Proveedor_Busqueda1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Pedido_Proveedor_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Pedido_Proveedor_Buscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_Pedido_ProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(eti_Pedido_Proveedor_CIF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_Pedido_ProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(eti_Pedido_Proveedor_DSocial))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pedido ");
        jLabel1.setOpaque(true);

        radGroup_Pedido.add(rad_Pedido_Cliente);
        rad_Pedido_Cliente.setSelected(true);
        rad_Pedido_Cliente.setText("Cliente");

        radGroup_Pedido.add(rad_Pedido_Proveedor);
        rad_Pedido_Proveedor.setText("Proveedor");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Articulos"));

        jButton1.setText(">>");

        jButton2.setText("<<");

        tbl_Pedido_ArticulosPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tbl_Pedido_ArticulosPedidos);

        tbl_Pedido_Articulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tbl_Pedido_Articulos);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Articulos");
        jLabel3.setOpaque(true);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Articulos Pedidos");
        jLabel9.setOpaque(true);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(94, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnl_Pedido_ClienteProveedorLayout = new javax.swing.GroupLayout(pnl_Pedido_ClienteProveedor);
        pnl_Pedido_ClienteProveedor.setLayout(pnl_Pedido_ClienteProveedorLayout);
        pnl_Pedido_ClienteProveedorLayout.setHorizontalGroup(
            pnl_Pedido_ClienteProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 652, Short.MAX_VALUE)
        );
        pnl_Pedido_ClienteProveedorLayout.setVerticalGroup(
            pnl_Pedido_ClienteProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 282, Short.MAX_VALUE)
        );

        btn_Pedido_Cancelar.setText("Cancelar");

        btn_Pedido_HacerPedido.setText("Hacer Pedido");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_Pedido_ClienteProveedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(rad_Pedido_Cliente)
                        .addGap(46, 46, 46)
                        .addComponent(rad_Pedido_Proveedor)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_Pedido_HacerPedido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Pedido_Cancelar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rad_Pedido_Cliente)
                    .addComponent(rad_Pedido_Proveedor))
                .addGap(6, 6, 6)
                .addComponent(pnl_Pedido_ClienteProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Pedido_Cancelar)
                    .addComponent(btn_Pedido_HacerPedido))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_Pedido_Cancelar;
    public javax.swing.JButton btn_Pedido_Cliente_Buscar;
    public javax.swing.JButton btn_Pedido_HacerPedido;
    public javax.swing.JButton btn_Pedido_Proveedor_Buscar;
    public javax.swing.JComboBox cbox_Pedido_Cliente_Busqueda;
    public javax.swing.JComboBox cbox_Pedido_Proveedor_Busqueda1;
    public javax.swing.JLabel eti_Pedido_Cliente_Apellidos;
    public javax.swing.JLabel eti_Pedido_Cliente_Correo;
    public javax.swing.JLabel eti_Pedido_Cliente_Dni;
    public javax.swing.JLabel eti_Pedido_Cliente_Domicilio;
    public javax.swing.JLabel eti_Pedido_Cliente_Nombre;
    public javax.swing.JLabel eti_Pedido_Cliente_Telefono;
    public javax.swing.JLabel eti_Pedido_Proveedor_CIF;
    public javax.swing.JLabel eti_Pedido_Proveedor_DSocial;
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JPanel pnl_Pedido_Cliente;
    public javax.swing.JPanel pnl_Pedido_ClienteProveedor;
    public javax.swing.JPanel pnl_Pedido_Proveedor;
    public javax.swing.ButtonGroup radGroup_Pedido;
    public javax.swing.JRadioButton rad_Pedido_Cliente;
    public javax.swing.JRadioButton rad_Pedido_Proveedor;
    public javax.swing.JTable tbl_Pedido_Articulos;
    public javax.swing.JTable tbl_Pedido_ArticulosPedidos;
    public javax.swing.JTable tbl_Pedido_Cliente_Busqueda;
    private javax.swing.JTable tbl_Pedido_Proveedor_Busqueda;
    public javax.swing.JTextField txt_Pedido_Cliente_Buscar;
    public javax.swing.JTextField txt_Pedido_Proveedor_Buscar;
    // End of variables declaration//GEN-END:variables
}
