package Hibernate;
// Generated 26-nov-2015 9:16:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Proveedor generated by hbm2java
 */
public class Proveedor  implements java.io.Serializable {


     private String cif;
     private String denominacionSocial;
     private String telefono;
     private String correo;
     private Set documentos = new HashSet(0);

    public Proveedor() {
    }

	
    public Proveedor(String cif, String denominacionSocial, String telefono, String correo) {
        this.cif = cif;
        this.denominacionSocial = denominacionSocial;
        this.telefono = telefono;
        this.correo = correo;
    }
    public Proveedor(String cif, String denominacionSocial, String telefono, String correo, Set documentos) {
       this.cif = cif;
       this.denominacionSocial = denominacionSocial;
       this.telefono = telefono;
       this.correo = correo;
       this.documentos = documentos;
    }
   
    public String getCif() {
        return this.cif;
    }
    
    public void setCif(String cif) {
        this.cif = cif;
    }
    public String getDenominacionSocial() {
        return this.denominacionSocial;
    }
    
    public void setDenominacionSocial(String denominacionSocial) {
        this.denominacionSocial = denominacionSocial;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public Set getDocumentos() {
        return this.documentos;
    }
    
    public void setDocumentos(Set documentos) {
        this.documentos = documentos;
    }




}


